apiVersion: metal3.io/v1alpha1
kind: HardwareClassification
metadata:
  name: hardwareclassification-sample
  namespace: metal3
  labels:
    hardwareclassification-sample: matches
spec:
  hardwareCharacteristics:
      cpu:
         architecture : "x86-64"
         minimumCount: 2
         maximumCount: 72
         minimumSpeedMHz: 1000
         maximumSpeedMHz: 3600
      disk:
         minimumCount: 1
         maximumCount: 8
         minimumIndividualSizeGB: 10
         maximumIndividualSizeGB: 3000
      ram:
         minimumSizeGB: 1
         maximumSizeGB: 180
      nic:
         vendor: "Intel"
         minimumCount: 1
         maximumCount: 7
      firmware:
         bios:
            vendor: "Dell Inc."
            version: "1.5.6"
      systemVendor:
         manufacturer: "Dell Inc."
         productName: "PowerEdge R640"



