apiVersion: metal3.io/v1alpha1
kind: HardwareClassification
metadata:
  name: hardwareclassification-sample
  namespace: metal3
  labels:
    hardwareclassification-sample: matches
spec:
  hardwareCharacteristics:
      cpu:
         minimumCount: 4
         maximumCount: 6
         minimumSpeedMHz: 2600
         maximumSpeedMHz: 3600
      disk:
         minimumCount: 1
         maximumCount: 8
         minimumIndividualSizeGB: 30
         maximumIndividualSizeGB: 50
      ram:
         minimumSizeGB: 4
         maximumSizeGB: 8
      nic:
         minimumCount: 1
         maximumCount: 7
